# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a35ticsg324-1L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/shlab_56/Desktop/lab67_printerror/lab6.cache/wt [current_project]
set_property parent.project_path C:/Users/shlab_56/Desktop/lab67_printerror/lab6.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:arty:part0:1.1 [current_project]
set_property ip_output_repo c:/Users/shlab_56/Desktop/lab67_printerror/lab6.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/shlab_56/Desktop/lab67_printerror/lab6.srcs/sources_1/imports/BinToHex.v
  C:/Users/shlab_56/Desktop/lab67_printerror/lab6.srcs/sources_1/imports/LCD_module.v
  C:/Users/shlab_56/Desktop/lab67_printerror/lab6.srcs/sources_1/imports/clk_divider.v
  C:/Users/shlab_56/Desktop/lab67_printerror/lab6.srcs/sources_1/imports/debounce.v
  C:/Users/shlab_56/Desktop/lab67_printerror/lab6.srcs/sources_1/imports/sd_card.v
  C:/Users/shlab_56/Desktop/lab67_printerror/lab6.srcs/sources_1/imports/sram.v
  C:/Users/shlab_56/Desktop/lab67_printerror/lab6.srcs/sources_1/imports/uart.v
  C:/Users/shlab_56/Desktop/lab67_printerror/lab6.srcs/sources_1/new/lab7.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/shlab_56/Desktop/lab67_printerror/lab6.srcs/constrs_1/new/lab6.xdc
set_property used_in_implementation false [get_files C:/Users/shlab_56/Desktop/lab67_printerror/lab6.srcs/constrs_1/new/lab6.xdc]


synth_design -top lab7 -part xc7a35ticsg324-1L


write_checkpoint -force -noxdef lab7.dcp

catch { report_utilization -file lab7_utilization_synth.rpt -pb lab7_utilization_synth.pb }
